# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 📌 High Order Overview                                                           │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ ➤ Code Format   // V.8.0                                                         │
# │ ➤ Status        // 🔒 LOCKED                                                     │
# │ ➤ Author(s)     // @migbash                                                      │
# │ ➤ Maintainer(s) // @migbash                                                      │
# │ ➤ Created on    // 08.22.2025                                                    │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 📝 Description                                                                   │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ BETARENA (Module)
# │ |: <insert-module-summary-here>
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 🧿 Labels (Deprecated)                                                           │
# │ 1. duplicate
# │ 2. dependencies
# │ 3. details missing
# │ 4. announcement
# │ 5. 🕸️ web3
# │ 6. 🔵 [I] sportmonks
# │ 7. 💠 [I] data
# ╰──────────────────────────────────────────────────────────────────────────────────╯

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - TYPE - PURE TYPE                                                    │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'type:bug'
  color: '#d73a4a'
  description:
    'Something is not working. Needs to be looked at.'
  aliases: [ '🐞 [A] bug', '💻 [TD] Desktop', '📱 [TD] Mobile / Tablet' ]
#
