# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 📌 High Order Overview                                                           │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ ➤ Code Format   // V.8.0                                                         │
# │ ➤ Status        // 🔒 LOCKED                                                     │
# │ ➤ Author(s)     // @migbash                                                      │
# │ ➤ Maintainer(s) // @migbash                                                      │
# │ ➤ Created on    // 08.22.2025                                                    │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 📝 Description                                                                   │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ BETARENA (Module)
# │ |: <insert-module-summary-here>
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 🧿 Labels (Deprecated)                                                           │
# │   - duplicate
# │   - dependencies
# │   - details missing
# │   - good first issue
# │   - announcement
# │   - 🕸️ web3
# │   - prod
# │   - invalid
# │   - backend
# ╰──────────────────────────────────────────────────────────────────────────────────╯

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ MISCELLENOUS                                                                │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'story'
  color: '#C5DEF5'
  description:
    'High-level description user story or a feature request.'
  aliases: [ 'story' ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - STATUS                                                              │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'status:review'
  color: '#15E5F8'
  description:
    '[Status] :: passive-active state, being inspected and checked.'
  aliases:
    [
      '⏳ [ST] validating',
      '🔄 [ST] background',
      # ARCHIVED / LEGACY
      'validating',
      '🔄 background',
      'hold'
    ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - PRIORITY                                                            │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'priority:high'
  color: '#A3F20A'
  description:
    '[Priority] :: high attention and accelerated resolving needed.'
  aliases:
    [
      '📣 [A] high priority',
      # ARCHIVED / LEGACY
      'high priority'
    ]
#

- name: 'priority:urgent'
  color: '#EE4B2B'
  description:
    '[Priority] :: super urgent resolving needed.'
  aliases: [ '🚨 [A] urgent' ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - TYPE - PROJECT SECTION                                              │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'section:frontend'
  color: '#D1BD3B'
  description:
    '[Section] :: frontend related issues.'
  aliases: [ '🎨 Frontend' ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - TYPE - PURE TYPE                                                    │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'type:documentation'
  color: '#FBCA04'
  description:
    '[Type] :: documentation related issues.'
  aliases: [ 'documentation' ]
#

- name: 'type:bug'
  color: '#DC143C'
  description:
    '[Type] :: something is not working as expected.'
  aliases:
    [
      '🐞 [A] bug',
      '💻 [TD] Desktop',
      '📱 [TD] Mobile / Tablet',
      # ARCHIVED / LEGACY
      'bug'
    ]
#

- name: 'type:enhancement'
  color: '#a2eeef'
  description:
    '[Type] :: new feature or request'
  aliases:
    [
      '🌟 [A] enhancement',
      # ARCHIVED / LEGACY
      'enhancement'
    ]
#

- name: 'type:optimization'
  color: '#FF5F1F'
  description:
    '[Type] :: improvement, optimazation of (1) throttle, (2) speed related issues.'
  aliases:
    [
      'ℹ️ [T] optimization',
      # ARCHIVED / LEGACY
      'optimization'
    ]
#

- name: 'type:3rd-party'
  color: '#FF5F1F'
  description:
    '[Type] :: issues related to 3rd party services, modules, libraries, APIs.'
  aliases:
    [
      '🔵 [I] sportmonks',
      '💠 [I] data',
      # ARCHIVED / LEGACY
      'sportmonks'
    ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ CI/CD WORKFLOW                                                              │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'semver:patch'
  color: '#FBCA04'
  description:
    '[CI] :: semver bump of type PATCH'
#

- name: 'semver:minor'
  color: '#FBCA04'
  description:
    '[CI] :: semver bump of type MINOR'
#

- name: 'semver:major'
  color: '#FBCA04'
  description:
    '[CI] :: semver bump of type MAJOR'
#
