# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 📌 High Order Overview                                                           │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ ➤ Code Format   // V.8.0                                                         │
# │ ➤ Status        // 🔒 LOCKED                                                     │
# │ ➤ Author(s)     // @migbash                                                      │
# │ ➤ Maintainer(s) // @migbash                                                      │
# │ ➤ Created on    // 08.22.2025                                                    │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 📝 Description                                                                   │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ BETARENA (Module)
# │ |: <insert-module-summary-here>
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 🧿 Labels (Deprecated)                                                           │
# │ 1. duplicate
# │ 2. dependencies
# │ 3. details missing
# │ 4. announcement
# │ 5. 🕸️ web3
# │ 6. 🔵 [I] sportmonks
# │ 7. 💠 [I] data
# ╰──────────────────────────────────────────────────────────────────────────────────╯

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ MISCELLENOUS                                                                │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'story'
  color: '#C5DEF5'
  description:
    'High-level description user story or a feature request.'
  aliases: [ 'story' ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - STATUS                                                              │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'status:review'
  color: '#15E5F8'
  description:
    'In a passive-active state. Being inspected and checked.'
  aliases:
    [
      '⏳ [ST] validating',
      '🔄 [ST] background',
      # ARCHIVED / LEGACY
      'validating',
      '🔄 background',
      'hold'
    ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - PRIORITY                                                            │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'priority:high'
  color: '#A3F20A'
  description:
    'Something that needs attention and accelerated resolving'
  aliases:
    [
      '📣 [A] high priority',
      # ARCHIVED / LEGACY
      'high priority'
    ]
#

- name: 'priority:urgent'
  color: '#823526'
  description:
    'An urgent action needed on something'
  aliases: [ '🚨 [A] urgent' ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - TYPE - PROJECT SECTION                                              │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'section:frontend'
  color: '#D1BD3B'
  description:
    'section for frontend related issues'
  aliases: [ '🎨 Frontend' ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ ISSUE - TYPE - PURE TYPE                                                    │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'type:documentation'
  color: '#FBCA04'
  description:
    'semver bump of type :|: patch'
  aliases: [ 'documentation' ]
#

- name: 'type:bug'
  color: '#d73a4a'
  description:
    'Something is not working. Needs to be looked at.'
  aliases:
    [
      '🐞 [A] bug',
      '💻 [TD] Desktop',
      '📱 [TD] Mobile / Tablet',
      # ARCHIVED / LEGACY
      'bug'
    ]
#

- name: 'type:enhancement'
  color: '#a2eeef'
  description:
    'New feature or request'
  aliases:
    [
      '🌟 [A] enhancement',
      # ARCHIVED / LEGACY
      'enhancement'
    ]
#

- name: 'type:optimization'
  color: '#FF5F1F'
  description:
    'Improvement, optimazation of (1) throttle, (2) speed related issues.'
  aliases:
    [
      'ℹ️ [T] optimization',
      # ARCHIVED / LEGACY
      'optimization'
    ]
#

# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 💠 │ CI/CD WORKFLOW                                                              │
# ╰──────────────────────────────────────────────────────────────────────────────────╯

- name: 'semver:patch'
  color: '#FBCA04'
  description:
    'semver bump of type :|: patch'
#

- name: 'semver:minor'
  color: '#FBCA04'
  description:
    'semver bump of type :|: minor'
#

- name: 'semver:major'
  color: '#FBCA04'
  description:
    'semver bump of type :|: major'
#
