version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["https://github.com/Betarena/scores/blob/dev/Dockerfile"]

[[analyzers]]
name = "javascript"
enabled = true