# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  scores_web:
    image: scores_web
    restart: always
    environment:
      PORT: ${PORT}
      VITE_HASURA_DB_URL: ${VITE_HASURA_DB_URL}
      VITE_HASURA_DB_TOKEN: ${VITE_HASURA_DB_TOKEN}
      VITE_FIREBASE_DB_API_KEY: ${VITE_FIREBASE_DB_API_KEY}
      VITE_FIREBASE_DB_AUTH_DOMAIN: ${VITE_FIREBASE_DB_AUTH_DOMAIN}
      VITE_FIREBASE_DB_PROJECT_ID: ${VITE_FIREBASE_DB_PROJECT_ID}
      VITE_FIREBASE_DB_DATABASE_URL: ${VITE_FIREBASE_DB_DATABASE_URL}
      VITE_REDIS_HOST: ${VITE_REDIS_HOST}
      VITE_REDIS_PORT: ${VITE_REDIS_PORT}
      VITE_REDIS_PASS: ${VITE_REDIS_PASS}
      VITE_REDIS_CACHE_DB: ${VITE_REDIS_CACHE_DB}
      VITE_REDIS_BULL_DB: ${VITE_REDIS_BULL_DB}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./certs:/certs # IMPORTANT
    ports:
      - 5055:5055
      - 443:443 # IMPORTANT
      - 80:80   # IMPORTANT