name: ⚡️ Feature request - Internal
description: New Feature Request by Internal Betarena Team
title: "[FEATURE]: "
labels: ["🌟 [A] enhancement", "🎨 Frontend"]
body:

- type: markdown
  attributes:
    value: |
      Please, fill out this form to submit a new `Feature Request` for the Betarena - Scores Platform.

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you are requesting. ([scores/issues](https://github.com/Betarena/scores/issues)).
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe the problem.
    description: A clear and concise description of what the problem is.
    placeholder: I am trying to do [...] but [...]
  validations:
    required: false

- type: checkboxes
  id: devices
  attributes:
    label: Feature request target platform
    options:
      - label: Mobile
        required: false
      - label: Tablet
        required: false
      - label: Laptop/Desktop
        required: false

- type: textarea
  attributes:
    label: 📝 DESCRIPTION
    description: |
      For frontend requests, we should add the information not only about the design but also the endpoints and all information that will be consumed by the frontend.
  validations:
    required: true

- type: 📸 WIDGET IMAGE
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the feature request here.
  validations:
    required: false

- type: textarea
  attributes:
    label: 🎬 INITIAL STATE
    description: |
      How the widget or feature behaves on the default state.
  validations:
    required: true

- type: textarea
  attributes:
    label: 💠 WIDGET DATA
    description: |
      How the widget or feature behaves on the default state.
    placeholder: |
      ➤ Hasura
        [...]
        🎏 TRANSLATIONS
        - [...]
      ➤ Firebase
        [...]
  validations:
    required: true

- type: textarea
  attributes:
    label: ⚡️ CACHE
    description: |
      How the widget or feature behaves on the default state.
  validations:
    required: true

- type: textarea
  attributes:
    label: 🔎 SEO
    description: |
      How the widget or feature behaves on the default state.
  validations:
    required: true

- type: textarea
  attributes:
    label: 📈 GOOGLE ANALYTICS EVENTS
    description: |
      How the widget or feature behaves on the default state.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      - First detected on:
      - Platform language:
      - Geo Location:

      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
