blank_issues_enabled: false
# contact_links:
#   - name: Issue with Frontend
#     url:  https://github.com/Betarena/scores/issues/new/choose
#     about: Please open issues relating to Frontend - Scores Platform.
