# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 📌 High Order Overview                                                           │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ ➤ Code Format   // V.8.0                                                         │
# │ ➤ Status        // 🔒 LOCKED                                                     │
# │ ➤ Author(s)     // @migbash                                                      │
# │ ➤ Maintainer(s) // @migbash                                                      │
# │ ➤ Created on    // <date-created>                                                │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 📝 Description                                                                   │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ BETARENA (Module)
# │ |: Docker Compose Configuration for Scores
# ╰──────────────────────────────────────────────────────────────────────────────────╯

services:

  # ╭──────────────────────────────────────────────────────────────────────────────────╮
  # │ 🟦 │ CONTAINER(s) for :: APPLICATION                                             │
  # ╰──────────────────────────────────────────────────────────────────────────────────╯

  nginx:
    ports:
      - 8080:8080 # Scores (production)
      - 8085:8085 # Scores (staging)
      - 8090:8090 # GoAccess
    volumes:
      # ╭─────
      # │ NOTE: IMPORTANT
      # │ |: volume for: configuration files
      # ╰─────
      - ./nginx/config/local:/etc/nginx/config:ro
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
  #
#
