# ╭──────────────────────────────────────────────────────────────────────────────────╮
# │ 📌 High Order Overview                                                           │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ ➤ Code Format   // V.8.0                                                         │
# │ ➤ Status        // 🔒 LOCKED                                                     │
# │ ➤ Author(s)     // @migbash                                                      │
# │ ➤ Maintainer(s) // @migbash                                                      │
# │ ➤ Created on    // <date-created>                                                │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ 📝 Description                                                                   │
# ┣──────────────────────────────────────────────────────────────────────────────────┫
# │ BETARENA (Module)
# │ |: Docker Compose Configuration for Cache - Sitemap Worker
# ╰──────────────────────────────────────────────────────────────────────────────────╯

services:

  # ╭──────────────────────────────────────────────────────────────────────────────────╮
  # │ 🟦 │ CONTAINER(s) for :: APPLICATION                                             │
  # ╰──────────────────────────────────────────────────────────────────────────────────╯

  nginx:
    ports:
      - 80:80   # Scores
      - 443:443 # Scores
      - 8080:8080 # GoAccess
    volumes:
      - ${HOME}/../etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #
#