# ╭──────────────────────────────────────────────────────────────────╮
# │ 🐙 GITHUB ACIONS CI/CD WORKFLOW                                  │
# ┣──────────────────────────────────────────────────────────────────┫
# │ Responsible for:                                                 │
# │ ➤ [1] auto-commenting of project pull-request.                   │
# ╰──────────────────────────────────────────────────────────────────╯

name: '📌 Pull-Request Open'

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:

  # ╭──────────────────────────────────────────────────────────────────╮
  # │ NOTE:                                                            │
  # │ ➤ [1] auto-commenting of project pull-request.                   │
  # ╰──────────────────────────────────────────────────────────────────╯

  add_comment:
    name: 'Add (PR) Comment'
    runs-on: ubuntu-22.04
    steps:

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            > [!IMPORTANT]
            > Please set a versioning label of either `semver:patch`, `semver:minor`, or `semver:major` to **THIS** `Pull-Request`.
          repo-token: ${{ secrets.GITHUB_TOKEN }}